version: '3'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile_server
    ports:
      - "8000:8000"

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile_client
    depends_on:
      - server
    volumes:
      - ./client-images:/data
